### ISSUE TITLE
Doesn't build with gcc 7.3

### ISSUE THREAD

**Issue by andreasg123** [njbradley/bcr-dist#4]
When running `python setup.py build` with gcc 7.3 (from Amazon Linux) in the path, the following compilation error occurs:

```
bcrdist/cmodule/bcrdistmodule.cc: In instantiation of ‘PyTypeObject py_bcell_vector_type<dsbcell>’:
bcrdist/cmodule/bcrdistmodule.cc:499:23:   required from here
bcrdist/cmodule/bcrdistmodule.cc:410:21: sorry, unimplemented: non-trivial designated initializers not supported
 static PyTypeObject py_bcell_vector_type = {
                     ^~~~~~~~~~~~~~~~~~~~
```

Ubuntu 18.04 comes with gcc 7.5 so that the error may occur there, too, but I didn't try it.

As an unrelated issue, it would be nice if dependencies were specified, especially more esoteric ones like `umap-learn`. Otherwise, it takes several attempts before all dependencies are satisfied.

**Comment by njbradley** [comment]
Hey @andreasg123, thanks for your pull request, hopefully that fixes your problems! Just to warn you, this project is still a work in progress, so there are probably more problems I haven't found. Be sure to let me know if I can help!
